language: ruby
rvm:
  - 2.2
before_script:
  - gem install awesome_bot
env:
  - allowed_dupes=CONTRIBUTING,mocaplatform,Awesome-Swift-Education,XCDYouTubeKit,SRGMediaPlayer
script:
  - awesome_bot README.md --allow-ssl --white-list $allowed_dupesgrowthpush,awesomelinkcounter
