language: ruby
rvm:
  - 2.2
before_script:
  - gem install awesome_bot
env:
  - allowed_dupes=CONTRIBUTING,mocaplatform,Awesome-Swift-Education,XCDYouTubeKit
script:
  - awesome_bot README.md --white-list $allowed_dupes,rephrase.io,reddit,littlebites,amazon,twilio,developer.apple,growthpush,iphonedevsdk,awesomelinkcounter,SRGMediaPlayer
